RoutineManagement/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]


# Configuring url for static files and images
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import static
from .views import home, teacherProfile, viewRoutine, createRoutine, registerCourse, registerRoom
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', home, name="home"),
    path('profile/', teacherProfile, name="teacher_profile"),
    path('admin-dash/', viewRoutine, name="admin_dash"),
    path('view-routine/', viewRoutine, name="view_routine"),
    path('create-routine/', createRoutine, name="create_routine"),
    path('course-register/', registerCourse, name="course_register"),
    path('room-register/', registerRoom, name="room_register"),

]

core/models.py
from django.db import models
from accounts.models import Teacher, TimeTable
from django.utils.translation import ugettext_lazy as _


class CourseManager(models.Manager):
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by('preference', 'course_code')
        return queryset


class Course(models.Model):
    TYPE_CHOICES = (
        ('THEORY', 'Theory'),
        ('LAB', 'Lab')
    )

    PREFERENCE_CHOICES = (
        ('MAJOR', 'Major'),
        ('MINOR', 'Non-Major')
    )

    SEMESTER_CHOICES = (
        ('11', '1/1'),
        ('12', '1/2'),
        ('21', '2/1'),
        ('22', '2/2'),
        ('31', '3/1'),
        ('32', '3/2'),
        ('41', '4/1'),
        ('42', '4/2'),
    )

    course_name = models.CharField(_('Course Name'), max_length=60)
    course_code = models.CharField(
        _('Course Code'), max_length=10, unique=True)
    course_type = models.CharField(
        _('Course Type'), max_length=6, choices=TYPE_CHOICES)
    course_credit = models.DecimalField(
        _('Course Credit'), max_digits=2, decimal_places=1)
    preference = models.CharField(
        _('Department Preference'), max_length=5, choices=PREFERENCE_CHOICES)
    semester = models.CharField(
        _('Semester'), max_length=2, choices=SEMESTER_CHOICES)
    teacher = models.ForeignKey(Teacher, on_delete=models.RESTRICT)
    objects = CourseManager()

    class Meta:
        verbose_name = _('course')
        verbose_name_plural = _('courses')

    def getCourseClassHours(self):
        if self.course_type == "THEORY":
            return int(self.course_credit)
        else:
            return int(self.course_credit) * 2

    def __str__(self):
        return self.course_code


class Room(models.Model):
    TYPE_CHOICES = (
        ('THEORY', 'Theory'),
        ('LAB', 'Lab')
    )

    room_id = models.CharField(max_length=8, unique=True)
    room_type = models.CharField(
        _('Room Type'), max_length=6, choices=TYPE_CHOICES)
    time_table = models.ManyToManyField(
        TimeTable, through='RoomEngagement', blank=True)

    class Meta:
        verbose_name = _('room')
        verbose_name_plural = _('rooms')

    def __str__(self):
        return self.room_id


class RoomEngagement(models.Model):
    STATUS_CHOICES = (
        ('FREE', 'FREE'),
        ('ENG', 'ENGAGED')
    )
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    time_table = models.ForeignKey(TimeTable, on_delete=models.CASCADE)
    status = models.CharField(
        _("Engagement Status"), max_length=4, choices=STATUS_CHOICES)

    class Meta:
        unique_together = [['room', 'time_table']]

    def __str__(self):
        return self.room.room_id + "_" + self.time_table.get_id()


class ClassManager(models.Manager):
    def classesOfSemester(self, semester):
        queryset = super().get_queryset().filter(semester=semester)
        return queryset


class Class(models.Model):
    SEMESTER_CHOICES = (
        ('11', '1/1'),
        ('12', '1/2'),
        ('21', '2/1'),
        ('22', '2/2'),
        ('31', '3/1'),
        ('32', '3/2'),
        ('41', '4/1'),
        ('42', '4/2'),
    )
    DAY_CHOICES = (
        ('SUN', 'Sunday'),
        ('MON', 'Monday'),
        ('TUE', 'Tuesday'),
        ('WED', 'Wednessday'),
        ('THU', 'Thursday')
    )
    STATUS_CHOICES = (
        ('SCHEDULED', 'Scheduled'),
        ('POSTPOND', 'Postpond')
    )

    semester = models.CharField(
        _('Semester'), max_length=2, choices=SEMESTER_CHOICES)
    day = models.CharField(_('day of the week'),
                           max_length=3, choices=DAY_CHOICES)
    time = models.CharField(_('time of the day'), max_length=5)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=9, choices=STATUS_CHOICES, default='SCHEDULED')

    objects = ClassManager()

    class Meta:
        verbose_name = _('class')
        verbose_name_plural = _('classes')

    def __str__(self):
        return self.course.course_code + "_" + self.room.room_id + "_" + self.day + self.time

core/forms.py
from django import forms
from .models import Course, Room


class CourseRegisterForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class RoomRegisterForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect
from django.forms import modelform_factory, formset_factory, modelformset_factory
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.decorators import admin_only, allowed_user
from accounts.models import User, Teacher, TeacherEngagement
from accounts.forms import TeacherProfileForm, UserProfileForm
from .models import Course, Room, Class
from .forms import CourseRegisterForm, RoomRegisterForm


@login_required(login_url='login')
@admin_only
def home(request):
    return render(request, "core/admin_dashboard.html")


@login_required(login_url='login')
@allowed_user(allowed_roles=['teacher'])
def teacherProfile(request):
    user = request.user
    teacher = request.user.teacher
    informationForm, engagementForm = None, None

    if request.method == 'POST':
        print(request.POST)
        if 'uploadEngagement' in request.POST:
            print("Upload Engagement")

            PartialEngagementForm = modelform_factory(
                Teacher, form=TeacherProfileForm, fields=("time_table",)
            )
            engagementForm = PartialEngagementForm(
                request.POST, instance=teacher)

            if engagementForm.is_valid():
                form = engagementForm.save()
                # Mark engaged in the database
                engagement = TeacherEngagement.objects.filter(
                    teacher=teacher, time_table__in=engagementForm.cleaned_data['time_table'])
                for i in range(len(engagement)):
                    engagement[i].status = 'ENG'
                    engagement[i].save()
            else:
                print(engagementForm.errors)

        elif 'updateInformation' in request.POST:
            informationForm = UserProfileForm(
                request.POST, request.FILES, instance=user)

            if "phone_number" in request.POST:
                PartialEngagementForm = modelform_factory(
                    Teacher, form=TeacherProfileForm, fields=("phone_number",)
                )
                engagementForm = PartialEngagementForm(
                    request.POST, instance=teacher)
                if engagementForm.is_valid():
                    engagementForm.save()
                else:
                    messages.error(
                        request, "Enter a valid phone number (e.g. 01711111111 or +8801711111111)")

            if informationForm.is_valid():
                informationForm.save()
            else:
                informationForm = informationForm

    if not informationForm:
        informationForm = UserProfileForm(instance=user)
    engagementForm = TeacherProfileForm(instance=teacher)
    context = {'informationForm': informationForm,
               'engagementForm': engagementForm}

    return render(request, "core/teacher_profile.html", context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin', 'student', 'teacher'])
def viewRoutine(request):
    return render(request, "core/admin_dashboard.html")


@login_required(login_url='login')
@admin_only
def createRoutine(request):
    ClassFormSet = modelformset_factory(
        Class, exclude=('status',), max_num=320, extra=2)
    formset = ClassFormSet()
    teachers = Teacher.objects.all()
    courses = Course.objects.all()
    rooms = Room.objects.all()
    classes11 = Class.objects.classesOfSemester("11")
    classes12 = Class.objects.classesOfSemester("12")
    classes21 = Class.objects.classesOfSemester("21")
    classes22 = Class.objects.classesOfSemester("22")
    classes31 = Class.objects.classesOfSemester("31")
    classes32 = Class.objects.classesOfSemester("32")
    classes41 = Class.objects.classesOfSemester("41")
    classes42 = Class.objects.classesOfSemester("42")

    if request.method == "POST":
        classForm = ClassFormSet(request.POST)
        if classForm.is_valid():
            classForm.save()
            return redirect('create_routine')
    context = {'teachers': teachers,
               'courses': courses,
               'rooms': rooms,
               'classes11': classes11,
               'classes12': classes12,
               'classes21': classes21,
               'classes22': classes22,
               'classes31': classes31,
               'classes32': classes32,
               'classes41': classes41,
               'classes42': classes42,
               'formset': formset}
    return render(request, "core/create_routine.html", context)


@login_required(login_url='login')
@admin_only
def registerCourse(request):
    form = CourseRegisterForm

    if request.method == 'POST':
        form = CourseRegisterForm(request.POST)
        if form.is_valid():
            course = form.save()
            course_code = form.cleaned_data.get('course_code')
            messages.success(
                request, "New Course ( " + course_code + " ) is registered !!", extra_tags='success')
            redirect('course_register')

    context = {'form': form}
    return render(request, "core/course_register.html", context)


@login_required(login_url='login')
@admin_only
def registerRoom(request):
    form = RoomRegisterForm

    if request.method == 'POST':
        form = RoomRegisterForm(request.POST)
        if form.is_valid():
            room = form.save()
            room_id = form.cleaned_data.get('room_id')
            messages.success(
                request, "New Room ( " + room_id + " ) is registered !!", extra_tags='success')
            redirect('room_register')

    context = {'form': form}
    return render(request, "core/room_register.html", context)

core/templates/core/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% block header %}
    {% endblock %}
    <style type="text/css">
        .popover {
            max-width: 100%;
            overflow-y: auto;
            z-index: 1000;
        }
    </style>

    <script>
        day_index = { 'SUN': 0, 'MON': 1, 'TUE': 2, 'WED': 3, 'THU': 4 }
        course_in_a_day = {
            '11SUN': [], '11MON': [], '11TUE': [], '11WED': [], '11THU': [],
            '12SUN': [], '12MON': [], '12TUE': [], '12WED': [], '12THU': [],
            '21SUN': [], '21MON': [], '21TUE': [], '21WED': [], '21THU': [],
            '22SUN': [], '22MON': [], '22TUE': [], '22WED': [], '22THU': [],
            '31SUN': [], '31MON': [], '31TUE': [], '31WED': [], '31THU': [],
            '32SUN': [], '32MON': [], '32TUE': [], '32WED': [], '32THU': [],
            '41SUN': [], '41MON': [], '41TUE': [], '41WED': [], '41THU': [],
            '42SUN': [], '42MON': [], '42TUE': [], '42WED': [], '42THU': [],
        }

        room_in_a_cell = {
            'SUN8': [], 'SUN9': [], 'SUN10': [], 'SUN11': [], 'SUN12': [], 'SUN1': [], 'SUN2': [], 'SUN3': [], 'SUN4': [],
            'MON8': [], 'MON9': [], 'MON10': [], 'MON11': [], 'MON12': [], 'MON1': [], 'MON2': [], 'MON3': [], 'MON4': [],
            'TUE8': [], 'TUE9': [], 'TUE10': [], 'TUE11': [], 'TUE12': [], 'TUE1': [], 'TUE2': [], 'TUE3': [], 'TUE4': [],
            'WED8': [], 'WED9': [], 'WED10': [], 'WED11': [], 'WED12': [], 'WED1': [], 'WED2': [], 'WED3': [], 'WED4': [],
            'THU8': [], 'THU9': [], 'THU10': [], 'THU11': [], 'THU12': [], 'THU1': [], 'THU2': [], 'THU3': [], 'THU4': [],
        }

        // remainingHrs = {
        //    'CSE143': 6, 'CSE133':3
        //}
        let remainingHrs = {}
        {% for course in courses %}
        remainingHrs["{{ course.course_code|cut:' '}}"] = parseInt("{{ course.getCourseClassHours }}")
        {% endfor %}

        console.log(remainingHrs)
    </script>
</head>

<body>

    {% block navbar %}
    {% include 'core/admin_navbar.html' %}
    {% endblock navbar %}

    <!--main content wrapper-->
    <div class="mcw">
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    <div class="card">
                        <div class="card-header text-center"><strong>Teachers' List</strong></div>
                        <div class="card-body">
                            <div class="accordion" id="teacher_list">
                                {% block teacher_list %}
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header text-center"><strong>Course List</strong></div>
                        <div class="card-body">
                            <div class="accordion" id="course_list">
                                {% block course_list %}
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    {% block js %}

    {% endblock %}

</body>

</html>

core/templates/core/admin_dashboard.html
{% extends 'core/admin_base.html' %}

{% block navbar %}
{% with current='home' %}{{ block.super }}{% endwith %}
{% endblock navbar %}

{% block body %}
<div class="row jumbotron">
    <div class="col-md-12">
        <h1>Hello Admin... Welcome to the Dashboard</h1>
    </div>
</div>
{% endblock body %}

core/templates/core/admin_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mr-5">
    <a href="{% url 'home' %}" style="text-decoration: none; color: darkslategray">
        <img id="nav_logo" src="{% static 'images\logo.png' %}" style="height: 30px; width: 30px">
        <strong>SUST CSE Routine</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item {% if current == 'home' %}active{% endif %}">
                <a class="nav-link" href="{% url 'home' %}">Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if current == 'create' %}active{% endif %}">
                <a class="nav-link" href="{% url 'create_routine' %}">Create Routine</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="registerDropdown" data-toggle="dropdown"
                    aria-haspopup="false" aria-expanded="false">
                    Register
                </a>
                <div class="dropdown-menu" aria-labelledby="registerDropdown">
                    <a class="dropdown-item" href="{% url 'course_register' %}">New Course</a>
                    <a class="dropdown-item" href="{% url 'room_register' %}">New Room</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="logoutDropdown" data-toggle="dropdown"
                    aria-haspopup="false" aria-expanded="false">
                    Settings
                </a>
                <div class="dropdown-menu" aria-labelledby="logoutDropdown">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">LogOut</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

core/templates/core/course_register.html
{% extends 'core/admin_base.html' %}
{% load crispy_forms_tags %}


{% block course_reg_active %}
class="active"
{% endblock course_reg_active %}

{% block body %}
<div class="row jumbotron">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }}" role="alert">
            <strong>{{ message }}</strong>
        </div>
        {% endfor %}
        {% if form.errors %}
        {% for error in field.errors %}
        <strong>{{ error|escape }}</strong>
        {% endfor %}
        {{ form.course_code.error }}
        {{ form.course_credit.error }}
        {% endif %}
        <div class="card">
            <h1 class="card-header">
                Register Course
            </h1>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            {{ form.course_name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.course_code|as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.course_type|as_crispy_field }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.course_credit|as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.preference|as_crispy_field }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.semester|as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.teacher|as_crispy_field }}</div>
                    </div>
                </div>
                <input class="btn btn-primary mb-4" id="registerCourse" value="Submit" type="submit">
            </form>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

{% endblock body %}

core/templates/core/home.html
{% extends 'accounts/base.html' %}

{% block body %}

<h3>Welcome!!! Admin</h3>

{% endblock %}

core/templates/core/teacher_profile.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>{{ request.user.get_full_name }}</title>
{% endblock %}
<style>
    .profile-pic {
        max-width: 50px;
        max-height: 50px;
        margin: 0 auto;
        border-radius: 50%;
    }
</style>
{% block body %}

<br>
<div class="row">
    <div class="col-md-3">
        <!-- Avatar and Name Div-->
        <div class="card card-body">
            <h3 style="text-align: center">{{ request.user.get_full_name }}</h3>
            <hr>
            <img class="profile-pic" src="{{request.user.avatar.url}}">
        </div>
        <!-- Avatar and Name Div Ends-->

        <br>

        <!-- Show Personal Info Div -->
        <div class="" style="display: block;" id="show_info">
            <div class="card card-body">
                <h5 class="card-title text-center">Personal Info</h5>
                <hr>
                <div class="row">
                    <i class="fas fa-envelope-square col-md-3 text-center"></i>
                    <span class="col-md-9">{{ informationForm.email.value }}</span>
                </div>
                <div class="row">
                    <i class="fas fa-phone col-md-3 text-center"></i>
                    <span class="col-md-9">{{ engagementForm.phone_number.value.as_national }}</span>
                </div>
                <div class="row">
                    <i class="fas fa-briefcase col-md-3 text-center"></i>
                    {% for x, y in engagementForm.fields.designation.choices %}
                    {% if engagementForm.designation.value == x %}
                    <span class="col-md-9" id="desg">
                        {{ y }}
                    </span>
                    {% endif %}
                    {% endfor %}
                </div>
                <br>
            </div>
            <span class="btn btn-primary mt-4" onclick="hideInfo()">Update Info</span>
        </div>
        <!-- Show Personal Info Div Ends-->
    </div>

    <!-- Update Engagement Div-->
    <div class="col-md-9">
        {% include 'core/schedule.html' %}
    </div>
    <!-- Update Engagement Div Ends-->
</div>
<br><br>
<div class="row">
    <!-- Update Personal Info Form -->
    <div class="col-md-6" style="display: none;" id="update_info">
        <div class="card card-body">
            <h5 class="card-title">Update Personal Information</h5>
            <hr>
            <form method="POST" action="" enctype="multipart/form-data" id="myForm">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{informationForm.first_name|as_crispy_field}}
                    </div>
                    <div class="col-md-6">
                        {{informationForm.last_name|as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{informationForm.email|as_crispy_field}}
                    </div>
                    <div class="col-md-6">
                        {{engagementForm.phone_number|as_crispy_field}}
                    </div>
                </div>
                {% for message in messages %}
                <div class="d-flex justify-content-center alert alert-danger mt-2 ml-4 mr-4" role="alert" id="message">
                    {{ message }}
                </div>
                {% endfor %}

                {{informationForm.avatar|as_crispy_field}}

                <input class="btn btn-primary" id="submit_info" type="submit" name="updateInformation" value="Update"
                    disabled>
                <span class="btn btn-primary ml-2" onclick="hideForm()">Cancel</span>
            </form>
        </div>
    </div>
    <!-- Update Personal Info Div Ends-->
</div>


<script>
    // If any error messages occur while submitting the form
    // this will hide the info div at very first and take user to the form.
    {% if messages or informationForm.errors %}
    hideInfo()
    {% endif %}
    // Error show ends //


    //------ Toggle show info and update info div strats--------//
    show_info = document.getElementById("show_info")
    update_info = document.getElementById("update_info")

    function hideInfo() {
        show_info.style.display = "none"
        update_info.style.display = "block"
    }

    function hideForm() {
        show_info.style.display = "block"
        update_info.style.display = "none"
    }
    //------ Toggle show info and update info div ends --------//


    //------ Enable Submit button if at-least one field is updated starts------//
    submit = document.getElementById("submit_info")
    let form = document.getElementById("myForm");
    form.addEventListener("input", function () {
        submit.disabled = false
    });
    //------ Enable Submit button if at-least one field is updated ends ------//


    //------ Mark Teachers engagement status as Danger in the cell starts------//
    const id_list = ["SUN8", "SUN9", "SUN10", "SUN11", "SUN12", "SUN2", "SUN3", "SUN4", "MON8", "MON9", "MON10", "MON11", "MON12", "MON2", "MON3", "MON4", "TUE8", "TUE9", "TUE10", "TUE11", "TUE12", "TUE2", "TUE3", "TUE4", "WED8", "WED9", "WED10", "WED11", "WED12", "WED2", "WED3", "WED4", "THU8", "THU9", "THU10", "THU11", "THU12", "THU2", "THU3", "THU4"]
    form_field = []
    $("#id_time_table option").each(function () {
        form_field.push($(this).filter(':selected').text())
    })
    for (let i = 0; i < id_list.length; i++) {
        cell = document.getElementById(id_list[i])
        for (let j = 0; j < form_field.length; j++) {
            if (form_field[j] == id_list[i]) {
                console.log(form_field[j])
                cell.classList.add("bg-danger")
                break;
            }
        }
    }
    //------ Mark Teachers engagement status as Danger in the cell ends ------//


    //------ Update Engagement Schedule in the Run-Time starts ------//
    update = document.getElementById("updateSchedule")
    upload = document.getElementById("uploadToAdmin")
    saved = document.getElementById("saveUpdate")
    footer = document.getElementById("cardFooter")
    title = document.getElementById("engagementTitle")

    function startUpdate() {
        update.style.display = "none"
        upload.style.display = "none"
        saved.style.display = "inline-block"
        footer.style.display = "inline-block"
        title.innerText = "Update Your Engagement"

        for (let i = 0; i < id_list.length; i++) {
            let cell = document.getElementById(id_list[i])
            cell.style.cursor = "pointer"
            cell.innerText = ""
            cell.addEventListener("click", showAlert);
        }
    }

    showAlert = function (event) {
        cell_id = event.target.id
        classList = event.target.classList
        if (classList.contains("bg-danger")) {
            classList.remove("bg-danger");
            $("#id_time_table option:contains(" + cell_id + ")").prop('selected', false)
        }
        else {
            classList.add("bg-danger");
            $("#id_time_table option:contains(" + cell_id + ")").prop('selected', true)
        }
    }

    function saveUpdate() {
        update.style.display = "inline-block"
        upload.style.display = "inline-block"
        saved.style.display = "none"
        footer.style.display = "none"
        title.innerText = "Your Engagement"

        for (let i = 0; i < id_list.length; i++) {
            cell = document.getElementById(id_list[i])
            cell.style.cursor = "default"
            cell.innerText = ""
            cell.removeEventListener("click", showAlert);
        }
    }
//------ Update Engagement Schedule in the Run-Time ends ------//
</script>
{% endblock %}

core/templates/core/view_routine.html
{% extends 'accounts/base.html' %}

{% block body %}

<h3>This is Your Routine Page</h3>


<a href="{% url 'create_routine' %}">Create Routine</a>

{% endblock %}